version: '3.8'
services:
  nextjs:
    build:
      context: ./next
    ports:
      - 3245:3245
    env_file:
      - ./next/.env.local
    networks:
      - proxy
  nginx:
    build:
      context: ./nginx
    ports:
      - 8090:80
networks:
  proxy:
    external:
      name: quoradocker_elastic